import os

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

APP_TITLE = "CS Explorer Studio"
APP_GEOMETRY = "1540x940"
STATE_FILE = os.path.join(BASE_DIR, "cs_explorer_state.json")
LOGO_FILE = os.path.join(BASE_DIR, "cs_explorer_logo_final.png")

SCHEMES = {
    "default": {
        "bg": "#f4f7ff",
        "surface": "#ffffff",
        "surface_alt": "#f7f3ff",
        "surface_dark": "#edf0ff",
        "nav": "#10182f",
        "nav_alt": "#1a2650",
        "nav_soft": "#121d3b",
        "primary": "#6c63ff",
        "primary_dark": "#5147ea",
        "primary_soft": "#ece9ff",
        "accent": "#20c997",
        "accent_soft": "#defbf2",
        "warning": "#ffb84d",
        "warning_soft": "#fff3dd",
        "text": "#182338",
        "muted": "#627089",
        "success": "#149f73",
        "success_soft": "#dcf8ef",
        "danger": "#e0527a",
        "danger_soft": "#ffe4ec",
        "border": "#d9def2",
        "code": "#eef1ff",
    },
    "contrast": {
        "bg": "#f4f4f4",
        "surface": "#ffffff",
        "surface_alt": "#ededed",
        "surface_dark": "#d9d9d9",
        "nav": "#000000",
        "nav_alt": "#1a1a1a",
        "nav_soft": "#000000",
        "primary": "#0047ff",
        "primary_dark": "#0030a8",
        "primary_soft": "#dce6ff",
        "accent": "#007f5f",
        "accent_soft": "#def2ea",
        "warning": "#af6d00",
        "warning_soft": "#fff1d1",
        "text": "#111111",
        "muted": "#2e2e2e",
        "success": "#0b6e4f",
        "success_soft": "#dff6ec",
        "danger": "#9f1239",
        "danger_soft": "#ffe3ea",
        "border": "#8a8a8a",
        "code": "#f1f1f1",
    },

    "dark": {
        "bg": "#0f1726",
        "surface": "#162033",
        "surface_alt": "#1b2940",
        "surface_dark": "#0f1a2e",
        "nav": "#0a1120",
        "nav_alt": "#16233f",
        "nav_soft": "#0e1830",
        "primary": "#7c8dff",
        "primary_dark": "#5f71f0",
        "primary_soft": "#26365f",
        "accent": "#33d2aa",
        "accent_soft": "#173a36",
        "warning": "#f3b562",
        "warning_soft": "#3f3219",
        "text": "#eef4ff",
        "muted": "#b5c1d9",
        "success": "#38c994",
        "success_soft": "#163a2e",
        "danger": "#ff7a92",
        "danger_soft": "#44202a",
        "border": "#33415f",
        "code": "#101a2d",
    },
}
